"""
Phase 3 Feature Extraction & Verification Script.
Amazon ML Challenge 2026: Business Entity Resolution.

Extracts pairwise features for candidate pairs generated by Phase 2 blocking,
merges ground truth labels, measures memory footprint/throughput, and logs
feature correlations to experiments/log.md.
"""

from __future__ import annotations

import gc
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import numpy as np
import pandas as pd

from blocking import CandidateIndex, extract_blocking_keys
from features import FEATURE_COLUMN_NAMES, build_pair_features_df, compute_pair_features
from normalize import NormalizedRecord, normalize_address, normalize_name


def load_normalized_lookup(
    source_tsv_path: str,
    source_tag: str = "source2",
) -> dict[str, NormalizedRecord]:
    """
    Loads a source TSV file and returns a dictionary of entity_id -> NormalizedRecord.
    """
    df = pd.read_csv(source_tsv_path, sep="\t", dtype=str).fillna("")
    lookup: dict[str, NormalizedRecord] = {}

    e_ids = df["entity_id"].tolist()
    names = df.get("business_name", pd.Series([""] * len(df))).fillna("").tolist()
    addrs = df.get("business_address", pd.Series([""] * len(df))).fillna("").tolist()
    ctrys = df.get("country", pd.Series([""] * len(df))).fillna("").tolist()

    for e_id, raw_name, raw_addr, ctry in zip(e_ids, names, addrs, ctrys):
        n_rec = normalize_name(raw_name)
        a_rec = normalize_address(raw_addr)
        lookup[e_id] = NormalizedRecord(
            entity_id=e_id,
            country=ctry,
            name=n_rec,
            address=a_rec,
        )

    return lookup


def run_feature_pipeline_on_split(
    val_parquet_path: str,
    data_dir: str,
    output_parquet_path: str,
    candidate_cap: int = 50,
    sample_size: Optional[int] = None,
) -> pd.DataFrame:
    """
    Generates candidate pairs and extracts pairwise features for validation entities.
    """
    t0 = time.time()
    print(f"Loading validation split from {val_parquet_path}...")
    val_df = pd.read_parquet(val_parquet_path)
    if sample_size and len(val_df) > sample_size:
        print(f"Subsampling {sample_size} validation entities for rapid verification...")
        val_df = val_df.sample(n=sample_size, random_state=42).reset_index(drop=True)

    print(f"Loaded {len(val_df):,} validation entities.")

    # 1. Load Source 1 text features for validation entities
    s1_tsv_path = os.path.join(data_dir, "train", "train_source1.tsv")
    print(f"Loading Source 1 metadata from {s1_tsv_path}...")
    s1_df = pd.read_csv(s1_tsv_path, sep="\t", dtype=str).fillna("")
    val_merged = val_df.merge(
        s1_df[["entity_id", "business_name", "business_address"]],
        left_on="source1_entity_id",
        right_on="entity_id",
        how="inner",
    )
    print(f"Merged {len(val_merged):,} validation entities with names and addresses.")

    # Ground truth lookup: source1_entity_id -> set of candidate entity IDs
    gt_lookup: dict[str, set[str]] = {}
    for s1, matched_str in zip(val_merged["source1_entity_id"], val_merged["matched_entity_ids"]):
        if pd.isna(matched_str) or not matched_str:
            gt_lookup[s1] = set()
        else:
            gt_lookup[s1] = set(x.strip() for x in str(matched_str).split(",") if x.strip())

    # 2. Build S1 records lookup
    print("Normalizing Source 1 validation records...")
    s1_lookup: dict[str, NormalizedRecord] = {}
    for e_id, ctry, raw_name, raw_addr in zip(
        val_merged["source1_entity_id"],
        val_merged["country"],
        val_merged["business_name"],
        val_merged["business_address"],
    ):
        s1_lookup[e_id] = NormalizedRecord(
            entity_id=e_id,
            country=ctry,
            name=normalize_name(raw_name),
            address=normalize_address(raw_addr),
        )

    # 3. Load and Normalize Candidate Pool (Source 2 and Source 3)
    s2_path = os.path.join(data_dir, "train", "train_source2.tsv")
    s3_path = os.path.join(data_dir, "train", "train_source3.tsv")
    print(f"Loading Candidate Pool (Source 2 & 3)...")
    cand_lookup: dict[str, NormalizedRecord] = {}
    cand_lookup.update(load_normalized_lookup(s2_path, source_tag="source2"))
    cand_lookup.update(load_normalized_lookup(s3_path, source_tag="source3"))
    print(f"Candidate pool loaded: {len(cand_lookup):,} candidates normalized.")

    # 4. Partition candidates by country and build inverted indexes
    country_candidates: dict[str, list[NormalizedRecord]] = {}
    for c_rec in cand_lookup.values():
        c_code = c_rec.country.strip().lower()
        if c_code not in country_candidates:
            country_candidates[c_code] = []
        country_candidates[c_code].append(c_rec)

    indexes: dict[str, CandidateIndex] = {}
    for c_code, c_list in country_candidates.items():
        print(f"Building Phase 2 blocking index for country '{c_code}' ({len(c_list):,} candidates)...")
        c_ids = [r.entity_id for r in c_list]
        names = [r.name.raw for r in c_list]
        addrs = [r.address.raw for r in c_list]
        indexes[c_code] = CandidateIndex(c_ids, names, addrs)

    # 5. Query blocking index to produce candidate pairs
    print("Generating candidate pairs via blocking retrieval...")
    t_block_start = time.time()
    pairs_list: list[dict[str, Any]] = []

    for s1_id, ctry, b_name, b_addr in zip(
        val_merged["source1_entity_id"],
        val_merged["country"],
        val_merged["business_name"],
        val_merged["business_address"],
    ):
        ctry_clean = ctry.strip().lower()
        idx = indexes.get(ctry_clean)
        if not idx:
            continue

        q_keys = extract_blocking_keys(b_name, b_addr)
        top_cands = idx.query(q_keys, candidate_cap=candidate_cap)

        s1_true_matches = gt_lookup.get(s1_id, set())

        for rank, (cand_id, score) in enumerate(top_cands, 1):
            is_match = 1 if cand_id in s1_true_matches else 0
            pairs_list.append({
                "source1_entity_id": s1_id,
                "candidate_entity_id": cand_id,
                "blocking_score": score,
                "candidate_rank": rank,
                "label": is_match,
            })

    t_block_elapsed = time.time() - t_block_start
    pairs_df = pd.DataFrame(pairs_list)
    print(f"Generated {len(pairs_df):,} candidate pairs in {t_block_elapsed:.2f}s ({len(pairs_df)/(t_block_elapsed+1e-5):,.0f} pairs/s).")

    positives = pairs_df["label"].sum() if "label" in pairs_df else 0
    print(f"Candidate pairs breakdown: {positives:,} true positives, {len(pairs_df)-positives:,} negatives (Positive rate: {positives/len(pairs_df)*100:.2f}%).")

    # 6. Extract Phase 3 Pairwise Features
    print(f"Extracting {len(FEATURE_COLUMN_NAMES)} pairwise features across {len(pairs_df):,} candidate pairs...")
    t_feat_start = time.time()
    features_df = build_pair_features_df(pairs_df, s1_lookup, cand_lookup, chunk_size=50000)
    t_feat_elapsed = time.time() - t_feat_start
    print(f"Feature extraction complete in {t_feat_elapsed:.2f}s ({len(features_df)/(t_feat_elapsed+1e-5):,.0f} pairs/s).")

    # 7. Check memory usage and Peak RSS
    try:
        import resource
        peak_rss_mb = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024.0
    except ImportError:
        peak_rss_mb = 0.0

    mem_df_mb = features_df.memory_usage(deep=True).sum() / (1024 * 1024)
    bytes_per_pair = (mem_df_mb * 1024 * 1024) / max(len(features_df), 1)
    print(f"\n=== MEMORY & PEAK RSS AUDIT ===")
    print(f"Candidate pairs evaluated: {len(features_df):,}")
    print(f"Features DataFrame in-memory: {mem_df_mb:.2f} MB ({bytes_per_pair:.1f} bytes/pair)")
    print(f"Process Peak RSS: {peak_rss_mb:.2f} MB ({peak_rss_mb / 1024:.2f} GB)")

    # Projection to full scale
    proj_86m_gb = (86_000_000 * bytes_per_pair) / (1024**3)
    proj_110m_gb = (110_000_000 * bytes_per_pair) / (1024**3)
    print(f"Projected Feature Table memory for 86M candidate pairs:  {proj_86m_gb:.2f} GB")
    print(f"Projected Feature Table memory for 110M candidate pairs: {proj_110m_gb:.2f} GB")

    # 8. Check Feature Correlations with Label for ALL 42 Features
    numeric_cols = [c for c in FEATURE_COLUMN_NAMES if c in features_df.columns]
    corrs = features_df[numeric_cols].apply(lambda x: x.corr(features_df["label"])).sort_values(ascending=False)
    print(f"\n=== ALL {len(corrs)} FEATURE CORRELATIONS WITH TRUE MATCH LABEL ===")
    print(f"{'Feature Name':<28} | {'Correlation (r)':<15} | {'Status'}")
    print("-" * 60)
    for col, val in corrs.items():
        if pd.isna(val):
            status = "CONSTANT (NaN)"
        elif abs(val) < 0.01:
            status = "FLAG: Near Zero (|r| < 0.01)"
        elif val > 0.30:
            status = "STRONG POSITIVE"
        elif val > 0.10:
            status = "MODERATE POSITIVE"
        elif val < -0.10:
            status = "NEGATIVE SIGNAL"
        else:
            status = "WEAK SIGNAL"
        r_str = f"{val:+.4f}" if not pd.isna(val) else "NaN"
        print(f"{col:<28} | {r_str:<15} | {status}")

    # 9. Save Parquet
    os.makedirs(os.path.dirname(output_parquet_path), exist_ok=True)
    features_df.to_parquet(output_parquet_path, index=False)
    print(f"\nSaved features Parquet to {output_parquet_path} ({os.path.getsize(output_parquet_path)/(1024*1024):.2f} MB).")
    print(f"Total pipeline elapsed time: {time.time() - t0:.2f}s.")

    return features_df


if __name__ == "__main__":
    data_dir = "dataset"
    val_path = "experiments/val_split.parquet"
    out_path = "experiments/val_features.parquet"

    # Default to 5000 sample for fast check if run directly, or full if requested
    sample = int(sys.argv[1]) if len(sys.argv) > 1 else 5000
    run_feature_pipeline_on_split(
        val_parquet_path=val_path,
        data_dir=data_dir,
        output_parquet_path=out_path,
        candidate_cap=50,
        sample_size=sample if sample > 0 else None,
    )
